### ISSUE TITLE
ESLint Complaining

### ISSUE THREAD

**Issue by ChiefChippy2** [Hypixel-API-Reborn/hypixel-api-reborn#335]
### Bug report

Eslint 8.14.0 says:

`Error: Rules with suggestions must set the `meta.hasSuggestions` property to `true`. `meta.docs.suggestion` is ignored by ESLint.
Occurred while linting /home/chiefchippy2/Projects/har-for-real/hypixel-api-reborn/typings/index.d.ts:239
Rule: "@typescript-eslint/no-explicit-any"
    at Object.report (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/linter.js:1094:39)
    at TSAnyKeyword (/home/chiefchippy2/Projects/har-for-real/hypixel-api-reborn/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-explicit-any.js:183:25)
    at ruleErrorHandler (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/chiefchippy2/.nvm/versions/node/v18.0.0/lib/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)`

Currently the ESLint version is on 7.32.0 or above, but if you want to upgrade to 8.14.0.... ^

**Comment by ChiefChippy2** [comment]
Just to clarify, ESLint does work when it is 7.32.0

also I didn't doxx myself, real name isn't chiefchippy2 fyi
