### ISSUE TITLE
TypeError: Hypixel.Bid is not a constructor

### ISSUE THREAD

**Issue by Zailer43** [Hypixel-API-Reborn/hypixel-api-reborn#58]
### Bug report
I don't know if it's my mistake or the api in case it's mine the mistake plus examples would help
- Error:
 ```
TypeError: hypixel_api_reborn_1.Bid is not a constructor
    at Object.<anonymous> (C:\Users\minec\Documents\GitHub\Auctions Flipper\index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path C:\Users\minec\Documents\GitHub\Auctions Flipper
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c "node index.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\minec\AppData\Local\npm-cache\_logs\2021-01-20T18_56_07_944Z-debug.log
```

- Code:
Index.ts
```
import { Bid } from 'hypixel-api-reborn';
//import { API_KEY } from './config.json';
//const hypixel = new Client(API_KEY);

const bid = new Bid({
    amount: 1,
    //at: Date(),
    //timestamp: Date.now()
})

console.log(bid)
```
tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by linearaccelerator** [comment]
Can you please share your entire code (preferably through hastebin)?

**Comment by ChiefChippy2** [comment]
1 why initialize a new Bid class???
2 it's called SkyblockAuctionBid. why? shrug.

**Comment by linearaccelerator** [comment]
> 
> 
> 2 it's called SkyblockAuctionBid. why? shrug.

long name

**Comment by ChiefChippy2** [comment]
thats what she said

**Comment by Zailer43** [comment]
> Can you please share your entire code (preferably through hastebin)?

the only thing I didn't pass was the package.json and config.json, but that's all the code, just start

**Comment by linearaccelerator** [comment]
why are you trying to create a new bid object manually anyways

**Comment by Zailer43** [comment]
I wanted to see it come back

**Comment by Zailer43** [comment]
I want to do something like [HyAuctions](https://auctions.craftlink.xyz/flipper) as it has the bid cost, lowest bin and bins outdated so it is not very effective, by the way I also want to be able to customize a minimum profit
